<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notification_1</name>
   <tag></tag>
   <elementGuidId>fd8d14a9-425d-48c3-941e-b97c53596022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/div/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.left-ul > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efd8c3dc-606e-4050-8c36-8118cf5a87d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>activeclassname</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>ef48298f-ad32-4af7-a2e6-8abe40d86d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/exam/notification</value>
      <webElementGuid>7115542c-e339-4d1a-ab68-9bf5ee1401c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notification</value>
      <webElementGuid>3d15c8a5-ef87-47ed-be57-0ef086796747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;container-fluid height-vh&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 border-right height-vh&quot;]/ul[@class=&quot;left-ul&quot;]/li[4]/a[1]</value>
      <webElementGuid>37e4ad54-ce8d-4c59-a859-61615e3df8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>499a018b-aa24-489b-b7ea-5a1e1ee396cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Notification')])[2]</value>
      <webElementGuid>85dfb8a8-b41c-4e7b-93c0-0ecc7d188631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Norms And Rules'])[3]/following::a[1]</value>
      <webElementGuid>1c8abe8e-4bdb-457b-a31f-993b694450af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result'])[2]/following::a[2]</value>
      <webElementGuid>3ad9a8fc-a42b-403d-9f75-0e0d82db3dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Norms And Rules'])[4]/preceding::a[1]</value>
      <webElementGuid>50e9b76c-6160-4a79-8a61-b7337f7443aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO RECORDS FOUND'])[1]/preceding::a[1]</value>
      <webElementGuid>461db709-c50a-4f6e-bc31-0f7dee48488c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/exam/notification')]</value>
      <webElementGuid>2fad821e-30fe-4b05-8a5b-26a26c21b25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[4]/a</value>
      <webElementGuid>ce14eee6-c87d-4041-9a97-6895beff7f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/exam/notification' and (text() = 'Notification' or . = 'Notification')]</value>
      <webElementGuid>507502be-7790-4dcc-a564-7eeb364f439a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
